service:
  name: notification

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  customEmail:
    handler: src/email/custom/handler.post
    events:
      - http:
          method: post
          path: /api/v1/email/custom
