service:
  name: notification

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: src/email/custom/handler.hello
    events:
      - http:
          method: get
          path: hello
